import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "DrinkMaster",
	description: "Generated by create next app",
};

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
			<body>
				<header>
					<Link href="/welcome">welcome</Link>
					<br />
					<Link href="/add">add</Link>
					<br />
					<Link href="/drinks">drinks</Link>
					<br />
					<Link href="/favorite">favorite</Link>
					<br />
					<Link href="/my">my</Link>
				</header>
				{children}
			</body>
		</html>
	);
}

//! export default function Layout({ dashboard, login }: { dashboard: React.ReactNode; login: React.ReactNode }) {
// 	const isLoggedIn = getUser();
// 	return isLoggedIn ? dashboard : login;
// }
