import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "DrinkMaster",
	description: "Generated by create next app",
};

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
			<body>
				RootLayout
				{children}
			</body>
		</html>
	);
}
